services:
  - type: web
    name: hrone-ecommerce-api
    env: python
    runtime: python-3.13.4
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB
        value: ecommerce