services:
  - type: web
    name: HRone_Ecommerce
    env: python
    # Be explicit about Python version
    pythonVersion: 3.11.4  
    buildCommand: >
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB
        value: ecommerce
    autoDeploy: true